spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/citronix
    username: citronix
    password: citronix
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
