spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/citronix
    username: citronix
    password: citronix
    driver-class-name: org.postgresql.Driver
    type: com.zaxxer.hikari.HikariDataSource

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  docker:
    compose:
      lifecycle-management: start_only

